# Generated by Django 3.2.9 on 2021-11-18 13:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_path',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='./'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='./'),
        ),
    ]
