# Generated by Django 3.2.9 on 2021-11-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211118_2249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
