# Generated by Django 3.2.9 on 2021-11-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
