# Generated by Django 3.2.9 on 2021-11-24 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='want',
            field=models.ManyToManyField(blank=True, related_name='user_wants', to=settings.AUTH_USER_MODEL),
        ),
    ]
