# Generated by Django 3.2.9 on 2021-11-18 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211118_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecoment',
            name='content',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
    ]
