# Generated by Django 3.2.9 on 2021-11-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_moviecoment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecoment',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
