# Generated by Django 3.2.9 on 2021-11-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_moviecoment_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecoment',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='coment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.moviecoment'),
            preserve_default=False,
        ),
    ]
