# Generated by Django 3.2.9 on 2021-11-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211119_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='coment',
        ),
        migrations.AddField(
            model_name='moviecoment',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
