# Generated by Django 3.2.9 on 2021-11-18 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20211119_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieComent',
            new_name='MovieComment',
        ),
    ]
