# Generated by Django 3.2.9 on 2021-11-23 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_moviecoment_moviecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
