# Generated by Django 3.2.9 on 2021-11-23 09:01

import birthday.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20211123_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='birthday',
            field=birthday.fields.BirthdayField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='birthday_dayofyear_internal',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True),
        ),
    ]
